# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer1.bqchain.com:
  orderer2.bqchain.com:
  orderer3.bqchain.com:
  orderer4.bqchain.com:
  orderer5.bqchain.com:
  peer0.org1.bqchain.com:
  peer1.org1.bqchain.com:
  peer0.org2.bqchain.com:
  peer1.org2.bqchain.com:

networks:
  byfn:

services:

  orderer1.bqchain.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LISTENPORT=8050
    container_name: orderer1.bqchain.com
    networks:
      - byfn
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/bqchain.com/orderers/orderer1.bqchain.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/bqchain.com/orderers/orderer1.bqchain.com/tls/:/var/hyperledger/orderer/tls
      - orderer1.bqchain.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  orderer2.bqchain.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LISTENPORT=8050
    container_name: orderer2.bqchain.com
    networks:
      - byfn
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/bqchain.com/orderers/orderer2.bqchain.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/bqchain.com/orderers/orderer2.bqchain.com/tls/:/var/hyperledger/orderer/tls
      - orderer2.bqchain.com:/var/hyperledger/production/orderer
    ports:
      - 8050:8050

  orderer3.bqchain.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LISTENPORT=9050
    container_name: orderer3.bqchain.com
    networks:
      - byfn
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/bqchain.com/orderers/orderer3.bqchain.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/bqchain.com/orderers/orderer3.bqchain.com/tls/:/var/hyperledger/orderer/tls
      - orderer3.bqchain.com:/var/hyperledger/production/orderer
    ports:
      - 9050:9050

  orderer4.bqchain.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LISTENPORT=10050
    container_name: orderer4.bqchain.com
    networks:
      - byfn
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/bqchain.com/orderers/orderer4.bqchain.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/bqchain.com/orderers/orderer4.bqchain.com/tls/:/var/hyperledger/orderer/tls
      - orderer4.bqchain.com:/var/hyperledger/production/orderer
    ports:
      - 10050:10050

  orderer5.bqchain.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LISTENPORT=11050
    container_name: orderer5.bqchain.com
    networks:
      - byfn
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/bqchain.com/orderers/orderer5.bqchain.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/bqchain.com/orderers/orderer5.bqchain.com/tls/:/var/hyperledger/orderer/tls
      - orderer5.bqchain.com:/var/hyperledger/production/orderer
    ports:
      - 11050:11050

  peer0.org1.bqchain.com:
    container_name: peer0.org1.bqchain.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.bqchain.com
    networks:
      - byfn

  peer1.org1.bqchain.com:
    container_name: peer1.org1.bqchain.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.bqchain.com
    networks:
      - byfn

  peer0.org2.bqchain.com:
    container_name: peer0.org2.bqchain.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.bqchain.com
    networks:
      - byfn

  peer1.org2.bqchain.com:
    container_name: peer1.org2.bqchain.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org2.bqchain.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.bqchain.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.bqchain.com/peers/peer0.org1.bqchain.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.bqchain.com/peers/peer0.org1.bqchain.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.bqchain.com/peers/peer0.org1.bqchain.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.bqchain.com/users/Admin@org1.bqchain.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric-samples/chaincode
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    extra_hosts:
      - "orderer1.bqchain.com:127.0.0.1"

    depends_on:
      - orderer1.bqchain.com
      - orderer2.bqchain.com
      - orderer3.bqchain.com
      - orderer4.bqchain.com
      - orderer5.bqchain.com
      - peer0.org1.bqchain.com
      - peer1.org1.bqchain.com
      - peer0.org2.bqchain.com
      - peer1.org2.bqchain.com
    networks:
      - byfn
